project:
  type: book

book:
  title: "Thinned Nonhomogeneous Poisson Processes for Presence-Only data"
  author: "Max Savery"
  chapters:
    - index.qmd
    - introduction.qmd
    - po_data.qmd
    - theory.qmd
    - data_generation.qmd
    - poisson-processes_presence-only.qmd
    - conclusion.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

date:  last-modified

execute:
  freeze: true